starting process...

2023-02-28 19:47:06.457624 - starting process...
2023-02-28 19:56:15.869580 - starting process...
2023-02-28 20:04:00.152328 - starting process...
2023-02-28 20:05:02.300198 - Err4: <class 'AttributeError'>; 'tuple' object has no attribute 'number_format'; ('tuple' object has no attribute 'number_format'), line: 422, in app.py | UTC: 2023-02-28 20:05:02.300198
2023-02-28 20:11:08.899887 - starting process...
2023-02-28 20:12:04.094541 - Err4: <class 'AttributeError'>; 'tuple' object has no attribute 'number_format'; ('tuple' object has no attribute 'number_format'), line: 422, in app.py | UTC: 2023-02-28 20:12:04.094541
2023-02-28 20:12:23.603110 - starting process...
2023-02-28 21:21:26.763077 - starting process...
2023-02-28 21:22:02.506487 - Err4: <class 'IndexError'>; list index out of range; (list index out of range), line: 352, in app.py | UTC: 2023-02-28 21:22:02.506487
2023-02-28 21:23:13.352575 - starting process...
2023-02-28 21:25:14.763982 - starting process...
2023-03-12 17:35:23.676943 - starting process...
2023-03-12 17:35:53.345357 - Err2: ERROR for: OTB
2023-03-12 17:36:22.728232 - starting process...
2023-03-12 17:36:54.312210 - Err2: ERROR for: OTB
2023-03-12 17:37:05.615003 - starting process...
2023-03-12 17:38:31.176967 - Err3: ERROR for: OTB
2023-03-12 17:39:39.247460 - starting process...
2023-03-12 17:41:04.528671 - Err3: ERROR for: OTB
2023-03-12 17:43:31.126989 - starting process...
2023-03-12 17:44:08.293108 - Err3: ERROR for: OTB
2023-03-12 17:44:48.553308 - starting process...
2023-03-12 17:46:12.869033 - Err3: ERROR for: OTB
2023-03-12 17:46:34.095699 - starting process...
2023-03-12 18:31:08.835227 - starting process...
2023-03-12 18:33:16.603901 - starting process...
2023-03-12 18:33:56.201772 - Err2: ERROR for: OTB
2023-03-12 18:34:12.268382 - starting process...
2023-03-12 18:34:41.147194 - Err2: ERROR for: OTB
2023-03-12 18:36:32.314331 - starting process...
2023-03-12 18:37:00.848375 - Err2: ERROR for: OTB
2023-03-12 18:39:47.217054 - starting process...
2023-03-12 18:40:51.661444 - Err2: ERROR for: OTB
2023-03-12 18:52:19.401343 - starting process...
2023-03-12 18:52:35.917888 - ERROR for: Total Rooms Budget
2023-03-19 07:49:27.852974 - starting process...
2023-03-19 07:49:54.186080 - Err2: ERROR for: OTA
2023-03-19 07:52:03.696055 - starting process...
2023-03-19 07:56:26.260953 - starting process...
2023-03-30 15:00:14.972864 - starting process...
2023-03-30 15:00:49.632454 - Err4: <class 'TypeError'>; unsupported operand type(s) for *: 'NoneType' and 'int'; (unsupported operand type(s) for *: 'NoneType' and 'int'), line: 359, in app.py | UTC: 2023-03-30 15:00:49.632454
2023-03-30 15:03:57.984130 - starting process...
2023-03-30 15:09:37.572128 - starting process...
2023-03-30 15:10:31.807113 - starting process...
2023-03-30 15:11:27.367382 - starting process...
2023-03-30 15:14:06.694567 - starting process...
2023-03-30 15:14:34.334012 - Err4: <class 'TypeError'>; int() argument must be a string, a bytes-like object or a real number, not 'NoneType'; (int() argument must be a string, a bytes-like object or a real number, not 'NoneType'), line: 237, in app.py | UTC: 2023-03-30 15:14:34.334012
2023-03-30 15:16:02.139919 - starting process...
2023-03-30 15:16:29.684996 - Err4: <class 'TypeError'>; int() argument must be a string, a bytes-like object or a real number, not 'NoneType'; (int() argument must be a string, a bytes-like object or a real number, not 'NoneType'), line: 238, in app.py | UTC: 2023-03-30 15:16:29.684996
2023-03-30 15:18:28.518828 - starting process...
2023-03-30 15:19:03.725825 - Err4: <class 'TypeError'>; unsupported operand type(s) for *: 'int' and 'NoneType'; (unsupported operand type(s) for *: 'int' and 'NoneType'), line: 364, in app.py | UTC: 2023-03-30 15:19:03.725825
2023-03-30 15:22:17.345097 - starting process...
2023-03-30 15:25:17.891129 - starting process...
2023-03-30 15:43:49.256092 - starting process...
2023-03-30 15:44:07.177620 - Err4: <class 'AttributeError'>; 'int' object has no attribute 'replace'; ('int' object has no attribute 'replace'), line: 206, in app.py | UTC: 2023-03-30 15:44:07.177620
2023-03-30 15:45:10.227865 - starting process...
2023-03-30 15:45:44.641747 - Err4: <class 'IndexError'>; list index out of range; (list index out of range), line: 372, in app.py | UTC: 2023-03-30 15:45:44.641747
2023-03-30 15:48:04.748381 - starting process...
2023-03-30 15:53:22.079906 - starting process...
2023-03-30 15:56:04.148967 - starting process...
2023-03-30 15:56:22.214863 - Err4: <class 'AttributeError'>; 'int' object has no attribute 'replace'; ('int' object has no attribute 'replace'), line: 209, in app.py | UTC: 2023-03-30 15:56:22.214863
2023-03-30 15:57:18.735283 - starting process...
2023-03-30 15:58:38.598294 - starting process...
2023-03-30 16:02:37.547071 - starting process...
2023-03-30 16:05:04.081527 - starting process...
2023-03-30 16:06:44.078084 - starting process...
2023-03-30 16:09:34.007929 - starting process...
2023-03-30 16:10:53.182573 - starting process...
