starting process...

2023-02-28 19:47:06.457624 - starting process...
2023-02-28 19:56:15.869580 - starting process...
2023-02-28 20:04:00.152328 - starting process...
2023-02-28 20:05:02.300198 - Err4: <class 'AttributeError'>; 'tuple' object has no attribute 'number_format'; ('tuple' object has no attribute 'number_format'), line: 422, in app.py | UTC: 2023-02-28 20:05:02.300198
2023-02-28 20:11:08.899887 - starting process...
2023-02-28 20:12:04.094541 - Err4: <class 'AttributeError'>; 'tuple' object has no attribute 'number_format'; ('tuple' object has no attribute 'number_format'), line: 422, in app.py | UTC: 2023-02-28 20:12:04.094541
2023-02-28 20:12:23.603110 - starting process...
2023-02-28 21:21:26.763077 - starting process...
2023-02-28 21:22:02.506487 - Err4: <class 'IndexError'>; list index out of range; (list index out of range), line: 352, in app.py | UTC: 2023-02-28 21:22:02.506487
2023-02-28 21:23:13.352575 - starting process...
2023-02-28 21:25:14.763982 - starting process...
2023-03-12 17:35:23.676943 - starting process...
2023-03-12 17:35:53.345357 - Err2: ERROR for: OTB
2023-03-12 17:36:22.728232 - starting process...
2023-03-12 17:36:54.312210 - Err2: ERROR for: OTB
2023-03-12 17:37:05.615003 - starting process...
2023-03-12 17:38:31.176967 - Err3: ERROR for: OTB
2023-03-12 17:39:39.247460 - starting process...
2023-03-12 17:41:04.528671 - Err3: ERROR for: OTB
2023-03-12 17:43:31.126989 - starting process...
2023-03-12 17:44:08.293108 - Err3: ERROR for: OTB
2023-03-12 17:44:48.553308 - starting process...
2023-03-12 17:46:12.869033 - Err3: ERROR for: OTB
2023-03-12 17:46:34.095699 - starting process...
